### Exploring train-test dataset (EDA)

In [ ]:
# importing required libraries
%pip install pandas numpy matplotlib

Collecting pandas
  Downloading pandas-2.3.3-cp310-cp310-win_amd64.whl.metadata (19 kB)
Collecting numpy
  Downloading numpy-2.2.6-cp310-cp310-win_amd64.whl.metadata (60 kB)
Collecting matplotlib
  Downloading matplotlib-3.10.9-cp310-cp310-win_amd64.whl.metadata (52 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ravichandran\anaconda3\envs\spotter-freight-rate-ml\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2026.5-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2026.5-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.2-cp310-cp310-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.65.0-cp310-cp310-win_amd64.whl.metadata (127 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.1-cp310-cp310-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\ravichandran\anaconda3\envs\spotter-freight-rate-ml\lib\site-packages (from matplotlib) (26.3)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-12.3.0-cp310-cp310-win_amd64.whl.metadata (9.3 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.3-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: six>=1.5 in c:\users\ravichandran\anaconda3\envs\spotter-freight-rate-ml\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.3-cp310-cp310-win_amd64.whl (11.3 MB)
   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
    --------------------------------------- 0.3/11.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.3 MB 1.0 MB/s eta 0:00:11
   - -------------------------------------- 0.5/11.3 MB 1.0 MB/s eta 0:00:11
   --- ------------------------------------ 1.0/11.3 MB 1.2 MB/s eta 0:00:09
   ---- ----------------------------------- 1.3/11.3 MB 1.2 MB/s eta 0:00:09
   ----- ---------------------------------- 1.6/11.3 MB 1.3 MB/s eta 0:00:08
   ------ --------------------------------- 1.8/11.3 MB 1.4 MB/s eta 0:00:07
   -------- ------------------------------- 2.4/11.3 MB 1.4 MB/s eta 0:00:07
   ---------- ----------------------------- 2.9/11.3 MB 1.5 MB/s eta 0:00:06
   ------------ --------------------------- 3.7/11.3 MB 1.7 MB/s eta 0:00:05
   --------------- ------------------------ 4.5/11.3 MB 1.9 MB/s eta 0:00:04
   ------------------ --------------------- 5.2/11.3 MB 2.1 MB/s eta 0:00:03
   --------------------- ------------------ 6.0/11.3 MB 2.2 MB/s eta 0:00:03
   ------------------------ --------------- 6.8/11.3 MB 2.4 MB/s eta 0:00:02
   --------------------------- ------------ 7.9/11.3 MB 2.6 MB/s eta 0:00:02
   ------------------------------ --------- 8.7/11.3 MB 2.6 MB/s eta 0:00:02
   -------------------------------- ------- 9.2/11.3 MB 2.6 MB/s eta 0:00:01
   ------------------------------------ --- 10.2/11.3 MB 2.7 MB/s eta 0:00:01
   ------------------------------------- -- 10.7/11.3 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------- 11.3/11.3 MB 2.8 MB/s  0:00:04
Downloading numpy-2.2.6-cp310-cp310-win_amd64.whl (12.9 MB)
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.9 MB 4.2 MB/s eta 0:00:03
   ----- ---------------------------------- 1.8/12.9 MB 4.8 MB/s eta 0:00:03
   -------- ------------------------------- 2.9/12.9 MB 4.7 MB/s eta 0:00:03
   ---------- ----------------------------- 3.4/12.9 MB 4.7 MB/s eta 0:00:03
   ------------- -------------------------- 4.2/12.9 MB 4.5 MB/s eta 0:00:02
   ----------------- ---------------------- 5.5/12.9 MB 4.5 MB/s eta 0:00:02
   ------------------- -------------------- 6.3/12.9 MB 4.3 MB/s eta 0:00:02
   ---------------------- ----------------- 7.3/12.9 MB 4.4 MB/s eta 0:00:02
   ------------------------- -------------- 8.1/12.9 MB 4.4 MB/s eta 0:00:02
   --------------------------- ------------ 8.9/12.9 MB 4.3 MB/s eta 0:00:01
   ------------------------------ --------- 9.7/12.9 MB 4.4 MB/s eta 0:00:01
   ---------------------------------- ----- 11.0/12.9 MB 4.4 MB/s eta 0:00:01
   ----------------------------------- ---- 11.5/12.9 MB 4.3 MB/s eta 0:00:01
   ------------------------------------ --- 11.8/12.9 MB 4.1 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.9 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------  12.8/12.9 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------- 12.9/12.9 MB 3.8 MB/s  0:00:03
Downloading matplotlib-3.10.9-cp310-cp310-win_amd64.whl (8.2 MB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.2 MB ? eta -:--:--
   ----- ---------------------------------- 1.0/8.2 MB 3.0 MB/s eta 0:00:03
   ------- -------------------------------- 1.6/8.2 MB 3.5 MB/s eta 0:00:02
   -------- ------------------------------- 1.8/8.2 MB 2.5 MB/s eta 0:00:03
   ----------- ---------------------------- 2.4/8.2 MB 2.5 MB/s eta 0:00:03
   --------------- ------------------------ 3.1/8.2 MB 2.6 MB/s eta 0:00:02
   ------------------- -------------------- 3.9/8.2 MB 2.8 MB/s eta 0:00:02
   ------------------------ --------------- 5.0/8.2 MB 3.1 MB/s eta 0:00:02
   ---------------------------- ----------- 5.8/8.2 MB 3.2 MB/s eta 0:00:01
   --------------------------------- ------ 6.8/8.2 MB 3.3 MB/s eta 0:00:01
   ---------------------------------- ----- 7.1/8.2 MB 3.1 MB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.2 MB 3.2 MB/s eta 0:00:01
   ---------------------------------------- 8.2/8.2 MB 3.1 MB/s  0:00:02
Downloading contourpy-1.3.2-cp310-cp310-win_amd64.whl (221 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.65.0-cp310-cp310-win_amd64.whl (1.6 MB)
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ------------------- -------------------- 0.8/1.6 MB 4.8 MB/s eta 0:00:01
   ---------------------------------------- 1.6/1.6 MB 4.2 MB/s  0:00:00
Downloading kiwisolver-1.5.1-cp310-cp310-win_amd64.whl (70 kB)
Downloading pillow-12.3.0-cp310-cp310-win_amd64.whl (7.2 MB)
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ----- ---------------------------------- 1.0/7.2 MB 5.6 MB/s eta 0:00:02
   ----------- ---------------------------- 2.1/7.2 MB 5.1 MB/s eta 0:00:02
   ------------------ --------------------- 3.4/7.2 MB 5.8 MB/s eta 0:00:01
   ----------------------- ---------------- 4.2/7.2 MB 5.4 MB/s eta 0:00:01
   ------------------------------ --------- 5.5/7.2 MB 5.5 MB/s eta 0:00:01
   ------------------------------------ --- 6.6/7.2 MB 5.5 MB/s eta 0:00:01
   ---------------------------------------- 7.2/7.2 MB 5.2 MB/s  0:00:01
Downloading pyparsing-3.3.3-py3-none-any.whl (126 kB)
Downloading pytz-2026.5-py2.py3-none-any.whl (506 kB)
Downloading tzdata-2026.5-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, pyparsing, pillow, numpy, kiwisolver, fonttools, cycler, pandas, contourpy, matplotlib

   ----------------------------------------  0/11 [pytz]
   ----------------------------------------  0/11 [pytz]
   ----------------------------------------  0/11 [pytz]
   ----------------------------------------  0/11 [pytz]
   ----------------------------------------  0/11 [pytz]
   --- ------------------------------------  1/11 [tzdata]
   --- ------------------------------------  1/11 [tzdata]
   --- ------------------------------------  1/11 [tzdata]
   --- ------------------------------------  1/11 [tzdata]
   --- ------------------------------------  1/11 [tzdata]
   --- ------------------------------------  1/11 [tzdata]
   ------- --------------------------------  2/11 [pyparsing]
   ---------- -----------------------------  3/11 [pillow]
   ---------- -----------------------------  3/11 [pillow]
   ---------- -----------------------------  3/11 [pillow]
   ---------- -----------------------------  3/11 [pillow]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   -------------- -------------------------  4/11 [numpy]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   --------------------- ------------------  6/11 [fonttools]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   -------------------------------- -------  9/11 [contourpy]
   ------------------------------------ --- 10/11 [matplotlib]
   ------------------------------------ --- 10/11 [matplotlib]
   ------------------------------------ --- 10/11 [matplotlib]
   ------------------------------------ --- 10/11 [matplotlib]
   ------------------------------------ --- 10/11 [matplotlib]
   ------------------------------------ --- 10/11 [matplotlib]
   ------------------------------------ --- 10/11 [matplotlib]
   ------------------------------------ --- 10/11 [matplotlib]
   ------------------------------------ --- 10/11 [matplotlib]
   ------------------------------------ --- 10/11 [matplotlib]
   ------------------------------------ --- 10/11 [matplotlib]
   ------------------------------------ --- 10/11 [matplotlib]
   ------------------------------------ --- 10/11 [matplotlib]
   ------------------------------------ --- 10/11 [matplotlib]
   ------------------------------------ --- 10/11 [matplotlib]
   ------------------------------------ --- 10/11 [matplotlib]
   ------------------------------------ --- 10/11 [matplotlib]
   ------------------------------------ --- 10/11 [matplotlib]
   ------------------------------------ --- 10/11 [matplotlib]
   ---------------------------------------- 11/11 [matplotlib]

Successfully installed contourpy-1.3.2 cycler-0.12.1 fonttools-4.65.0 kiwisolver-1.5.1 matplotlib-3.10.9 numpy-2.2.6 pandas-2.3.3 pillow-12.3.0 pyparsing-3.3.3 pytz-2026.5 tzdata-2026.5
Note: you may need to restart the kernel to use updated packages.

In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [18]:
freight = pd.read_csv(r"C:\Users\Ravichandran\OneDrive\Desktop\spotter-freight-rate-ml\data\train-test.csv")
freight = freight.copy()
freight

,load_id,pickup,delivery,pickup_lat,pickup_lon,delivery_lat,delivery_lon,distance,equipment,weight,date,market_index,quote_signal,posted_rate
0,TR-000001,Richmond,Baltimore,38.09122,-76.78906,38.16908,-72.74564,274.3,Dry Van,30658.0,2025-01-01,0.95684,2.39595,645.41
1,TR-000002,Richmond,Philadelphia,38.09122,-76.78906,39.22317,-72.96710,280.5,Reefer,17555.0,2025-01-01,0.97623,2.43355,679.97
2,TR-000003,Philadelphia,Green Bay,39.22317,-72.96710,44.30296,-87.52871,967.8,Dry Van,31721.0,2025-01-01,1.00971,1.84491,1802.54
3,TR-000004,Hartford,Atlanta,39.55328,-72.18051,34.84933,-86.28940,965.4,Dry Van,32333.0,2025-01-01,0.94518,1.87712,1827.28
4,TR-000005,Dallas,Nashville,31.83025,-94.38343,35.29479,-88.08915,541.9,Reefer,35183.0,2025-01-01,0.98480,2.56300,1380.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47995,TR-047996,Reno,Baton Rouge,39.54838,-118.64843,30.50134,-92.65374,1830.9,Flatbed,31786.0,2025-10-31,0.98865,2.05626,3787.32
47996,TR-047997,Greensboro,Memphis,35.98195,-82.78379,35.56802,-89.52871,445.8,Reefer,37465.0,2025-10-31,1.03034,1.51985,1171.93
47997,TR-047998,Greensboro,Cincinnati,35.98195,-82.78379,37.15706,-86.77499,267.9,Flatbed,24528.0,2025-10-31,1.00846,1.46954,713.36
47998,TR-047999,Memphis,Reno,35.56802,-89.52871,39.54838,-118.64843,1901.3,Flatbed,37581.0,2025-10-31,1.00014,2.05132,3987.46
47999,TR-048000,Bakersfield,Baltimore,33.28832,-116.67935,38.16908,-72.74564,2860.4,Dry Van,28359.0,2025-10-31,1.07073,2.31578,5264.84

In [29]:
freight.columns.to_list()

['load_id',
 'pickup',
 'delivery',
 'pickup_lat',
 'pickup_lon',
 'delivery_lat',
 'delivery_lon',
 'distance',
 'equipment',
 'weight',
 'date',
 'market_index',
 'quote_signal',
 'posted_rate']

In [20]:
freight.info()
freight.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48000 entries, 0 to 47999
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   load_id       48000 non-null  object
 1   pickup        48000 non-null  object
 2   delivery      48000 non-null  object
 3   pickup_lat    48000 non-null  float64
 4   pickup_lon    48000 non-null  float64
 5   delivery_lat  48000 non-null  float64
 6   delivery_lon  48000 non-null  float64
 7   distance      48000 non-null  float64
 8   equipment     48000 non-null  object
 9   weight        47700 non-null  float64
 10  date          48000 non-null  object
 11  market_index  47626 non-null  float64
 12  quote_signal  48000 non-null  float64
 13  posted_rate   48000 non-null  float64
dtypes: float64(9), object(5)
memory usage: 5.1+ MB

,pickup_lat,pickup_lon,delivery_lat,delivery_lon,distance,weight,market_index,quote_signal,posted_rate
count,48000.000000,48000.000000,48000.000000,48000.000000,48000.000000,47700.000000,47626.000000,48000.000000,48000.000000
mean,35.647545,-90.928964,35.641175,-90.857310,1135.856654,31028.844004,1.083387,2.062468,2373.980682
std,4.315285,13.482431,4.317199,13.476589,728.564416,9391.440620,0.168091,0.291391,1486.493245
min,28.357650,-121.698490,28.357650,-121.698490,70.000000,-47500.000000,0.676390,0.692280,57.220000
25%,31.986910,-98.400590,31.986910,-98.400590,550.400000,25800.000000,0.949670,1.891030,1251.555000
50%,35.294790,-88.089150,35.294790,-87.528710,953.300000,31436.500000,1.055800,2.055750,2030.760000
75%,39.411040,-83.285060,39.411040,-83.285060,1645.525000,37018.000000,1.219590,2.221685,3330.750000
max,44.302960,-69.500000,44.302960,-69.500000,3439.800000,47500.000000,1.467780,3.610350,25533.000000

In [33]:
freight.shape

(48000, 14)

In [34]:
freight.isnull().sum()

load_id           0
pickup            0
delivery          0
pickup_lat        0
pickup_lon        0
delivery_lat      0
delivery_lon      0
distance          0
equipment         0
weight          300
date              0
market_index    374
quote_signal      0
posted_rate       0
dtype: int64

In [68]:
print(f"Duplicated rows : {freight.duplicated().sum()} ")

Duplicated rows : 0

In [71]:
# checking duplicate load ID's
print("Duplicate load_id = " , freight["load_id"].duplicated().sum())

Duplicate load_id =  0

In [ ]:
# checking date form
freight["date"]

0        2025-01-01
1        2025-01-01
2        2025-01-01
3        2025-01-01
4        2025-01-01
            ...
47995    2025-10-31
47996    2025-10-31
47997    2025-10-31
47998    2025-10-31
47999    2025-10-31
Name: date, Length: 48000, dtype: object

In [56]:
#checking unique values in pickup
print(freight["pickup"].value_counts())
print(freight["pickup"].unique())

pickup
Oklahoma City    1242
Lexington        1209
Bakersfield      1193
Fort Wayne       1170
Hartford         1150
                 ...
Detroit           337
Washington        337
St. Louis         318
Las Vegas         277
Dallas            276
Name: count, Length: 64, dtype: int64
['Richmond' 'Philadelphia' 'Hartford' 'Dallas' 'Phoenix' 'Fresno'
 'San Francisco' 'Bakersfield' 'Albuquerque' 'Harrisburg' 'Mobile'
 'Nashville' 'Detroit' 'Albany' 'New Orleans' 'Reno' 'Austin'
 'Chattanooga' 'Cincinnati' 'Syracuse' 'Atlanta' 'Oklahoma City'
 'Lexington' 'Los Angeles' 'Providence' 'Madison' 'El Paso' 'Washington'
 'Amarillo' 'Green Bay' 'Memphis' 'Baton Rouge' 'Kansas City' 'Fort Wayne'
 'Charleston' 'Columbia' 'Grand Rapids' 'Jacksonville' 'Corpus Christi'
 'Birmingham' 'Milwaukee' 'Tampa' 'Raleigh' 'Indianapolis' 'Baltimore'
 'Boston' 'San Antonio' 'Montgomery' 'Buffalo' 'New York' 'Houston'
 'Dayton' 'Toledo' 'Greensboro' 'Tulsa' 'Savannah' 'Shreveport' 'Lubbock'
 'St. Louis' 'Little Rock' 'Louisville' 'Salt Lake City' 'Las Vegas'
 'Tucson']

In [62]:
#checking unique values in delivery
print(freight["delivery"].value_counts())
print(freight["delivery"].unique())

delivery
Lexington      1197
Fort Wayne     1176
Baton Rouge    1167
Bakersfield    1156
Hartford       1143
               ...
St. Louis       344
Birmingham      318
Detroit         307
Dallas          306
Las Vegas       292
Name: count, Length: 64, dtype: int64
['Baltimore' 'Philadelphia' 'Green Bay' 'Atlanta' 'Nashville'
 'Corpus Christi' 'San Antonio' 'Kansas City' 'Montgomery' 'Phoenix'
 'Fresno' 'Lexington' 'El Paso' 'Syracuse' 'Louisville' 'Baton Rouge'
 'Bakersfield' 'Albuquerque' 'Cincinnati' 'Oklahoma City' 'Mobile'
 'Fort Wayne' 'Lubbock' 'New Orleans' 'Columbia' 'Hartford' 'Chattanooga'
 'New York' 'Amarillo' 'Harrisburg' 'Las Vegas' 'Salt Lake City'
 'Richmond' 'Charleston' 'Reno' 'Milwaukee' 'Jacksonville' 'Albany'
 'Indianapolis' 'Memphis' 'Dayton' 'Greensboro' 'Shreveport' 'Buffalo'
 'Grand Rapids' 'Austin' 'Houston' 'Raleigh' 'Madison' 'St. Louis' 'Tampa'
 'Boston' 'Tulsa' 'Tucson' 'Providence' 'Birmingham' 'Toledo'
 'Los Angeles' 'San Francisco' 'Little Rock' 'Detroit' 'Washington'
 'Dallas' 'Savannah']

In [ ]:
# for one hot encoding checking how many values equipment conatins 
freight['equipment'].unique()

array(['Dry Van', 'Reefer', 'Flatbed'], dtype=object)

In [ ]:
#checking whether distance  contains negative values
negative_distance = (freight['distance']<0).any().sum()
print("")
print("Negative distance = ", negative_distance)

Negative distance =  0